"""empty message

Revision ID: 226196717d87
Revises: d3db2ef9787d
Create Date: 2023-11-06 14:42:32.358942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226196717d87'
down_revision = 'd3db2ef9787d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.String(length=12), nullable=True, comment='모델 class ID'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_column('class_id')

    # ### end Alembic commands ###
