"""empty message

Revision ID: 5e655e4187ae
Revises: 
Create Date: 2023-11-07 11:41:51.037637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e655e4187ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('img_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', sa.Float(), nullable=False, comment='분석 결과 평균 정확도'))

    with op.batch_alter_table('tag_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', sa.Float(), nullable=False, comment='분석 정확도'))

    with op.batch_alter_table('user_log', schema=None) as batch_op:
        batch_op.drop_column('rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='분석 결과 평균 정확도'))

    with op.batch_alter_table('tag_set', schema=None) as batch_op:
        batch_op.drop_column('rate')

    with op.batch_alter_table('img_set', schema=None) as batch_op:
        batch_op.drop_column('rate')

    # ### end Alembic commands ###
