"""empty message

Revision ID: 883779d179b9
Revises: e30e569886f7
Create Date: 2023-11-01 15:52:33.433412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883779d179b9'
down_revision = 'e30e569886f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine',
    sa.Column('MED_ID', sa.Text(), nullable=False),
    sa.Column('Name', sa.Text(), nullable=False),
    sa.Column('ThubLink', sa.Text(), nullable=False),
    sa.Column('Effect_Type', sa.Text(), nullable=False),
    sa.Column('Effect', sa.Text(), nullable=False),
    sa.Column('Usage_Type', sa.Text(), nullable=False),
    sa.Column('Usage', sa.Text(), nullable=False),
    sa.Column('Caution_Type', sa.Text(), nullable=False),
    sa.Column('Caution', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('MED_ID')
    )
    op.create_table('user',
    sa.Column('USR_ID', sa.Text(), nullable=False),
    sa.Column('Password', sa.Text(), nullable=False),
    sa.Column('Name', sa.Text(), nullable=False),
    sa.Column('Birthday', sa.DateTime(), nullable=False),
    sa.Column('Gender', sa.Text(), nullable=False),
    sa.Column('Phone', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('USR_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('medicine')
    # ### end Alembic commands ###
