"""empty message

Revision ID: b1a401b98c53
Revises: b8eeb94d4d36
Create Date: 2023-11-06 15:53:42.763285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1a401b98c53'
down_revision = 'b8eeb94d4d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbLink', sa.String(length=255), nullable=True, comment='썸네일 위치'))
        batch_op.drop_column('thubLink')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thubLink', mysql.VARCHAR(length=255), nullable=True, comment='썸네일 위치'))
        batch_op.drop_column('thumbLink')

    # ### end Alembic commands ###
