"""empty message

Revision ID: b8eeb94d4d36
Revises: 226196717d87
Create Date: 2023-11-06 14:44:42.896369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8eeb94d4d36'
down_revision = '226196717d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.alter_column('effect',
               existing_type=mysql.TEXT(),
               nullable=True,
               existing_comment='효능')
        batch_op.alter_column('usage',
               existing_type=mysql.TEXT(),
               nullable=True,
               existing_comment='용법')
        batch_op.alter_column('caution',
               existing_type=mysql.TEXT(),
               nullable=True,
               existing_comment='주의사항')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.alter_column('caution',
               existing_type=mysql.TEXT(),
               nullable=False,
               existing_comment='주의사항')
        batch_op.alter_column('usage',
               existing_type=mysql.TEXT(),
               nullable=False,
               existing_comment='용법')
        batch_op.alter_column('effect',
               existing_type=mysql.TEXT(),
               nullable=False,
               existing_comment='효능')

    # ### end Alembic commands ###
