"""empty message

Revision ID: d3db2ef9787d
Revises: 
Create Date: 2023-11-06 14:41:14.228405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3db2ef9787d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_log',
    sa.Column('check_log_id', sa.String(length=12), nullable=False, comment='사진 분석 로그 ID'),
    sa.Column('user_log_id', sa.String(length=12), nullable=False, comment='사진 전송 로그 ID'),
    sa.Column('img_id', sa.String(length=12), nullable=False, comment='이미지 ID'),
    sa.Column('med_id', sa.String(length=12), nullable=True, comment='분석결과 의약품 ID'),
    sa.Column('start_x', sa.Float(), nullable=True, comment='좌표 x1'),
    sa.Column('start_y', sa.Float(), nullable=True, comment='좌표 y1'),
    sa.Column('end_x', sa.Float(), nullable=True, comment='좌표 x2'),
    sa.Column('end_y', sa.Float(), nullable=True, comment='좌표 y2'),
    sa.Column('rate', sa.Integer(), nullable=True, comment='분석 결과 정확도'),
    sa.Column('date', sa.DateTime(), nullable=False, comment='분석날짜'),
    sa.PrimaryKeyConstraint('check_log_id')
    )
    op.create_table('id_seq',
    sa.Column('ID', sa.String(length=3), nullable=False, comment='키 앞자리 세자리'),
    sa.Column('seq', sa.Integer(), nullable=False, comment='키 번호'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('img_set',
    sa.Column('img_id', sa.String(length=12), nullable=False, comment='이미지 ID'),
    sa.Column('user_id', sa.String(length=12), nullable=True, comment='이미지 출처 ID'),
    sa.Column('img_dir', sa.String(length=40), nullable=False, comment='이미지 저장 장소'),
    sa.Column('train_cnt', sa.Integer(), nullable=False, comment='학습에 사용된 횟수'),
    sa.Column('date', sa.DateTime(), nullable=False, comment='저장된 날짜'),
    sa.PrimaryKeyConstraint('img_id')
    )
    op.create_table('medicine',
    sa.Column('med_id', sa.String(length=12), nullable=False, comment='의약품 DB ID'),
    sa.Column('name', sa.String(length=30), nullable=False, comment='의약품 이름'),
    sa.Column('thumbLink', sa.String(length=255), nullable=True, comment='썸네일 위치'),
    sa.Column('effect_type', sa.String(length=2), nullable=False, comment='코로나키트 K 일반약품 N'),
    sa.Column('effect', sa.Text(), nullable=False, comment='효능'),
    sa.Column('usage_type', sa.String(length=2), nullable=False, comment='코로나키트 K 일반약품 N'),
    sa.Column('usage', sa.Text(), nullable=False, comment='용법'),
    sa.Column('caution_type', sa.String(length=2), nullable=False, comment='코로나키트 K 일반약품 N'),
    sa.Column('caution', sa.Text(), nullable=False, comment='주의사항'),
    sa.PrimaryKeyConstraint('med_id')
    )
    op.create_table('tag_set',
    sa.Column('tag_id', sa.String(length=12), nullable=False, comment='태그 ID'),
    sa.Column('img_id', sa.String(length=12), nullable=False, comment='이미지 ID'),
    sa.Column('med_id', sa.String(length=12), nullable=False, comment='태깅 의약품 ID'),
    sa.Column('start_x', sa.Float(), nullable=True, comment='좌표 x1'),
    sa.Column('start_y', sa.Float(), nullable=True, comment='좌표 y1'),
    sa.Column('end_x', sa.Float(), nullable=True, comment='좌표 x2'),
    sa.Column('end_y', sa.Float(), nullable=True, comment='좌표 y2'),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(length=12), nullable=False, comment='유저 ID'),
    sa.Column('password', sa.String(length=200), nullable=True, comment='유저 패스워드'),
    sa.Column('name', sa.String(length=20), nullable=True, comment='유저 이름'),
    sa.Column('birthday', sa.DateTime(), nullable=True, comment='유저 생년월일'),
    sa.Column('gender', sa.String(length=2), nullable=True, comment='유저 성별'),
    sa.Column('phone', sa.String(length=17), nullable=True, comment='유저 전화번호'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_log',
    sa.Column('user_log_id', sa.String(length=12), nullable=False, comment='사진 전송 로그 ID'),
    sa.Column('user_id', sa.String(length=12), nullable=False, comment='유저 ID'),
    sa.Column('img_id', sa.String(length=12), nullable=False, comment='이미지 ID'),
    sa.Column('rate', sa.Integer(), nullable=False, comment='분석 결과 평균 정확도'),
    sa.Column('date', sa.DateTime(), nullable=False, comment='전송날짜'),
    sa.PrimaryKeyConstraint('user_log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_log')
    op.drop_table('user')
    op.drop_table('tag_set')
    op.drop_table('medicine')
    op.drop_table('img_set')
    op.drop_table('id_seq')
    op.drop_table('check_log')
    # ### end Alembic commands ###
